-- Create sensor_data table
CREATE TABLE IF NOT EXISTS public.sensor_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    temperature NUMERIC,
    gas_value NUMERIC,
    flame_state NUMERIC,
    fire_status BOOLEAN DEFAULT false,
    fire_severity TEXT DEFAULT 'CRITICAL',
    buzzer BOOLEAN DEFAULT false,
    humidity NUMERIC,
    device_online BOOLEAN DEFAULT false,
    temperature_sensor BOOLEAN DEFAULT false,
    smoke_sensor BOOLEAN DEFAULT false,
    flame_sensor BOOLEAN DEFAULT false,
    wifi_connected BOOLEAN DEFAULT false,
    pump_status BOOLEAN DEFAULT false,
    camera_status TEXT DEFAULT 'offline',
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.sensor_data ENABLE ROW LEVEL SECURITY;

-- Create Policies
-- Allow public select/read access to all records
CREATE POLICY "Allow public read access" 
ON public.sensor_data 
FOR SELECT 
USING (true);

-- Allow public insert/write access (typically written by ESP32 or backend)
CREATE POLICY "Allow public insert access" 
ON public.sensor_data 
FOR INSERT 
WITH CHECK (true);

-- Allow public update access (for updates to states)
CREATE POLICY "Allow public update access" 
ON public.sensor_data 
FOR UPDATE 
USING (true)
WITH CHECK (true);

-- Enable Realtime replication for sensor_data table
ALTER PUBLICATION supabase_realtime ADD TABLE public.sensor_data;
